### ISSUE TITLE
ReferenceError: google is not defined

### ISSUE THREAD

**Issue by kubriel** [Jam3/google-panorama-by-id#2]
var service = new google.maps.StreetViewService()
              ^

ReferenceError: google is not defined
    at Object.<anonymous> (~/google-panorama-by-id/demo/index.js:5:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by cheapsteak** [comment]
The google maps sdk needs to already be loaded in your app

Follow these steps first https://developers.google.com/maps/documentation/javascript/get-api-key

Make sure the script tag for the Google Maps SDK is injected before your app bundle
